project_id = "cvuyglhivifusdahoztd"

[functions.update-class-status]
verify_jwt = false

[functions.check-expired-attendance-links]
verify_jwt = false

[functions.check-expired-attendance-links.schedule]
cron = "*/5 * * * *"

[functions.create-establishment]
verify_jwt = false

[functions.send-invitation]
verify_jwt = true

[functions.accept-invitation]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = true

[functions.send-bulk-email]
verify_jwt = true
